name: todoproviderdb_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  path: ^1.9.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  sqflite: ^2.3.3+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
   - assets\loginImage.png
   - assets\signupImage.png
   - assets\person.png
